export default {
  singleQuote: true,
  printWidth: 250,
  importOrder: [
    '^node*',
    '^vite$',
    '^react',
    '<THIRD_PARTY_MODULES>',
    '^@front-monorepo-react/(.*)$',
    '^@/plugins/(.*)$',
    '^@/stores/(.*)$',
    '^@/api/(.*)$',
    '^@/contexts/(.*)$',
    '^@/hooks/(.*)$',
    '^@/types(.*)$',
    '^@/constants/(.*)$',
    '^@/components/(.*)$',
    '^@/pages/(.*)$',
    '^@/utils/(.*)$',
    '^@/assets/(.*)$',
    '^[./].*(\\.module)?\\.scss$',
    '^[./].*(\\.module)?\\.css$',
    '^[./].*\\.tsx?$',
    '^[./].*\\.jsx?$',
    '^[./]',
  ],
  importOrderSortSpecifiers: true,
  plugins: ['@trivago/prettier-plugin-sort-imports'],
};
